Add support for selecting TLS version v1.2 or v1.3
Mellanox/iperf_ssl pull request #1
Opened 2020-05-19 13:37 UTC by hselasky

2020-06-07 06:30 UTC, BorisPis requested changes

2020-06-07 06:30 UTC, BorisPis commented on src/Settings.cpp
> +{"tls",        required_argument, NULL, 'E'},
Please use optional_argument to maintain backward comparability

2020-06-07 06:30 UTC, BorisPis commented on src/Settings.cpp
> +                SSL_library_init();
Let's try to remove duplicate code here and below

2020-06-08 09:09 UTC, hselasky commented on src/Settings.cpp
> +{"tls",        required_argument, NULL, 'E'},
Fixed.

2020-06-08 09:09 UTC, hselasky commented on src/Settings.cpp
> +                SSL_library_init();
Fixed.

2020-08-24 08:58 UTC, hselasky commented
Can this be merged now?

2020-08-24 09:27 UTC, BorisPis approved these changes

2021-11-01 12:07 UTC, merged